# ==========================
# 🚀 Hugging Face Space Build Config
# Stable push / retry protection for large containers (StudioCore)
# ==========================

build:
  dockerfile: Dockerfile          # используем стандартный Dockerfile
  timeout: 2400                   # увеличивает таймаут сборки до 40 минут
  retries: 3                      # при обрыве соединения делает до 3 повторов

# Дополнительно можно указать флаг автокэша
# (ускоряет повторные билды и снижает нагрузку на push)
space:
  hardware: cpu
  enable_cache: true

# (опционально) можно явно прописать runtime
# runtime:
#   python_version: "3.10"
#   command: "python app.py"