# ================================
# 🤖 Hugging Face Space Config
# ================================
build:
  dockerfile: Dockerfile
  timeout: 2400
  retries: 5
  push_retries: 5
space:
  hardware: cpu
  enable_cache: true
  python_version: "3.10"
  secrets: {}
  variables: {}